import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Use – PayCalc Pro | Salary Calculator Website',
  description: 'Terms of Use for PayCalc Pro. Read our terms governing use of the free Indian salary calculator website, calculators, content, and advertisements.',
  alternates: { canonical: 'https://paycalcpro.online/terms' },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <section className="bg-slate-900 text-white py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Use</h1>
          <p className="text-slate-400">Last updated: May 24, 2026 | Effective: May 2026</p>
        </div>
      </section>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8 text-slate-700 leading-relaxed">

        <div className="card p-8">
          <p className="text-slate-600 leading-relaxed">
            These Terms of Use ("Terms") govern your access to and use of PayCalc Pro, a free salary calculator website operated at paycalcpro.online ("the Site", "we", "us", "our"). By accessing or using the Site, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use the Site.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">1. Nature of the Service</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            PayCalc Pro provides free, browser-based salary calculators for Indian salaried employees. Our calculators cover CTC to in-hand salary conversion, income tax estimation, EPF/PF corpus projection, HRA exemption calculation, gratuity calculation, and notice period buyout cost estimation.
          </p>
          <p className="text-slate-600 leading-relaxed mb-4">
            All calculators are provided for <strong>informational and educational purposes only</strong>. Results generated by our calculators are estimates based on standard assumptions, publicly available tax rules, and commonly used salary structures. They are not a substitute for professional financial, legal, or tax advice tailored to your specific circumstances.
          </p>
          <p className="text-slate-600 leading-relaxed">
            You use the Site and its calculators entirely at your own risk. PayCalc Pro does not verify, endorse, or guarantee the accuracy of results for your specific employer's salary structure, state-level taxes, or individual deductions.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">2. Accuracy and Limitations</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            We make every reasonable effort to keep our calculators accurate and updated with the latest tax rules, EPF interest rates, and salary structure norms. However, we make <strong>no warranty, express or implied</strong>, about the accuracy, completeness, reliability, or fitness for a particular purpose of any calculation result or content on the Site.
          </p>
          <p className="text-slate-600 leading-relaxed mb-4">
            Key limitations you should be aware of:
          </p>
          <ul className="space-y-2 text-slate-600">
            <li className="flex gap-2"><span className="text-slate-400">•</span> Tax laws change with every Union Budget — there may be a delay between legislative changes and our updates.</li>
            <li className="flex gap-2"><span className="text-slate-400">•</span> Our calculators assume standard salary structures (50% basic, industry-standard HRA). Your company may use a different structure.</li>
            <li className="flex gap-2"><span className="text-slate-400">•</span> State-specific professional tax rates, additional surcharges, or company-specific benefits are not fully accounted for.</li>
            <li className="flex gap-2"><span className="text-slate-400">•</span> Results are based on current-year rules and may not reflect retrospective tax amendments.</li>
          </ul>
          <p className="text-slate-600 leading-relaxed mt-4">
            Always verify critical financial decisions with a qualified Chartered Accountant or your company's HR/finance department.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">3. Acceptable Use</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            You may use PayCalc Pro for personal, non-commercial salary calculation and educational purposes. You agree not to:
          </p>
          <ul className="space-y-2 text-slate-600">
            <li className="flex gap-2"><span className="text-slate-400">•</span> Use the Site for any unlawful purpose or in violation of applicable Indian or international laws.</li>
            <li className="flex gap-2"><span className="text-slate-400">•</span> Scrape, crawl, or systematically download content from the Site using automated means without our written permission.</li>
            <li className="flex gap-2"><span className="text-slate-400">•</span> Attempt to reverse-engineer, modify, or create derivative works from our calculator algorithms or code.</li>
            <li className="flex gap-2"><span className="text-slate-400">•</span> Introduce malicious code, viruses, or any content that could damage, disable, or impair the Site.</li>
            <li className="flex gap-2"><span className="text-slate-400">•</span> Use our content or brand name in a way that implies official endorsement or affiliation without permission.</li>
            <li className="flex gap-2"><span className="text-slate-400">•</span> Reproduce our blog articles, guides, or calculator outputs for commercial resale without attribution and written permission.</li>
          </ul>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">4. Intellectual Property</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            All content on PayCalc Pro, including but not limited to text, articles, blog posts, salary guides, calculator design, user interface, source code, algorithms, graphics, and branding, is the exclusive property of PayCalc Pro and is protected under applicable intellectual property laws of India.
          </p>
          <p className="text-slate-600 leading-relaxed">
            You may share links to our pages and quote short excerpts with proper attribution (e.g., "Source: paycalcpro.online"). You may not reproduce, republish, or redistribute our content in full without written permission. Embedding our calculators on other websites is not permitted.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">5. Third-Party Advertising</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            PayCalc Pro displays third-party advertisements through Google AdSense (Publisher ID: ca-pub-7840512374734019). These advertisements are clearly labelled "Advertisement" and are selected and served by Google's automated systems, not by PayCalc Pro.
          </p>
          <p className="text-slate-600 leading-relaxed mb-4">
            We are not responsible for the content, accuracy, or claims made in advertisements. Clicking on an advertisement will take you to a third-party website governed by that site's own terms and privacy policy. We do not endorse any products, services, or companies advertised on this Site unless explicitly stated.
          </p>
          <p className="text-slate-600 leading-relaxed">
            Advertisements are never placed in ways designed to trick users into clicking them. The layout of our calculators and content is designed to clearly separate editorial content from advertising.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">6. Limitation of Liability</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            To the maximum extent permitted by applicable law, PayCalc Pro, its owners, contributors, and operators shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of your access to, use of, or inability to use the Site or its calculators.
          </p>
          <p className="text-slate-600 leading-relaxed">
            This includes but is not limited to: errors or omissions in calculator results, financial decisions made based on calculator outputs, loss of data, or any other matter relating to the Site. Your sole remedy for dissatisfaction with the Site or any content is to stop using the Site.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">7. Disclaimer of Professional Advice</h2>
          <p className="text-slate-600 leading-relaxed">
            Nothing on PayCalc Pro constitutes financial, tax, investment, legal, or accounting advice. The calculators and articles on this Site are for general informational and educational purposes only. For decisions involving your tax filing, salary negotiation, investment strategy, or financial planning, consult a qualified Chartered Accountant, financial advisor, or HR professional who can assess your specific circumstances.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">8. Links to Third-Party Websites</h2>
          <p className="text-slate-600 leading-relaxed">
            Our Site may contain links to external websites such as the Income Tax Department (incometax.gov.in), EPFO (epfindia.gov.in), or other government and financial resources. These links are provided for your convenience and reference. We have no control over the content, accuracy, or availability of external sites. Linking to a third-party site does not imply endorsement of that site or its content.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">9. Changes to Terms</h2>
          <p className="text-slate-600 leading-relaxed">
            We reserve the right to modify these Terms of Use at any time at our sole discretion. Changes will be effective immediately upon posting to the Site with an updated "Last updated" date. Your continued use of the Site after any changes constitutes your acceptance of the modified Terms. We encourage you to review these Terms periodically.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">10. Governing Law and Jurisdiction</h2>
          <p className="text-slate-600 leading-relaxed">
            These Terms of Use are governed by and construed in accordance with the laws of India, without regard to its conflict of law principles. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts of India. If any provision of these Terms is found to be unenforceable, the remaining provisions will remain in full force and effect.
          </p>
        </div>

        <div className="card p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-4">11. Contact</h2>
          <p className="text-slate-600 leading-relaxed">
            For questions about these Terms of Use, to report content issues, or for any other inquiries, please contact us:
          </p>
          <div className="mt-4 bg-slate-50 rounded-xl p-4">
            <p className="font-semibold text-slate-900">PayCalc Pro</p>
            <p className="text-slate-600">Website: paycalcpro.online</p>
            <p className="text-slate-600">Email: contact.paycalcpro@gmail.com</p>
          </div>
        </div>

        <div className="text-center">
          <Link href="/" className="btn-secondary">Back to Home</Link>
        </div>

      </div>
    </div>
  )
}
